import React from "react";
import MandateAuthenticate from "@/components/functional/MandateAuthenticate";

export const metadata = {
    title: 'Write Blog | Bloggios',
    description: 'Generated by Next.js',
}

export default function BlogWriteLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            <MandateAuthenticate />
            {children}
        </>
    )
}