import React from "react";
import MandateAuthenticate from "@/components/functional/MandateAuthenticate";
import AuthenticatedNavbar from "@/components/custom/navbars/AuthenticatedNavbar";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function AuthLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            <MandateAuthenticate />
            <AuthenticatedNavbar />
            {children}
        </>
    )
}
