import React from "react";
import DynamicNavbarProvider from "@/components/custom/navbars/DynamicNavbarProvider";

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function AuthLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            <DynamicNavbarProvider />
            {children}
        </>
    )
}
